#!/bin/bash

# Health Monitor - Installation Script
# Installs all components on a clean Ubuntu/Debian system

set -euo pipefail  # Exit on error / unset vars / pipeline errors

echo "🚀 Health Monitor - Installation Script"
echo "========================================"

# Helpers
require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "❌ Missing required command: $1"
    exit 1
  }
}

prompt_if_empty() {
  local var_name="$1"
  local prompt="$2"
  local current="${!var_name:-}"
  if [[ -z "$current" ]]; then
    read -r -p "$prompt" current
    export "$var_name=$current"
  fi
}

version_ge() {
  # Compare semver-ish strings: returns 0 if $1 >= $2
  # shellcheck disable=SC2206
  local IFS=.
  local a=($1) b=($2)
  for i in 0 1 2; do
    local ai=${a[i]:-0} bi=${b[i]:-0}
    if (( ai > bi )); then return 0; fi
    if (( ai < bi )); then return 1; fi
  done
  return 0
}

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo "❌ This script must be run as root" 
   exit 1
fi

# Variables
INSTALL_DIR="/opt/health-monitor"
SERVICE_USER="health-monitor"
DOMAIN="${DOMAIN:-}"  # e.g. monitor.example.com
EMAIL="${EMAIL:-}"    # e.g. admin@example.com
SKIP_CERTBOT="${SKIP_CERTBOT:-0}"  # set to 1 for internal CA / no internet

prompt_if_empty DOMAIN "Enter your domain (e.g. monitor.example.com): "
if [[ "$SKIP_CERTBOT" != "1" ]]; then
  prompt_if_empty EMAIL "Enter an email for certbot (e.g. admin@example.com): "
fi

validate_domain() {
  # Minimal sanity check (not a full RFC validator)
  [[ "$1" =~ ^[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?)+$ ]]
}

validate_email() {
  # Minimal sanity check
  [[ "$1" =~ ^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$ ]]
}

until validate_domain "$DOMAIN"; do
  echo "❌ Invalid domain: $DOMAIN"
  prompt_if_empty DOMAIN "Enter a valid domain (e.g. monitor.example.com): "
done

if [[ "$SKIP_CERTBOT" != "1" ]]; then
  until validate_email "$EMAIL"; do
    echo "❌ Invalid email: $EMAIL"
    prompt_if_empty EMAIL "Enter a valid email for certbot (e.g. admin@example.com): "
  done
fi

echo "📦 Installing system dependencies..."
apt-get update
apt-get install -y python3 python3-pip python3-venv nodejs npm nginx certbot python3-certbot-nginx docker.io docker-compose git openssl

echo "👤 Creating service user..."
if ! id "$SERVICE_USER" &>/dev/null; then
    useradd -r -s /bin/false $SERVICE_USER
    echo "✅ User $SERVICE_USER created"
else
    echo "ℹ️  User $SERVICE_USER already exists"
fi

echo "📂 Creating installation directory..."
mkdir -p $INSTALL_DIR
cd $INSTALL_DIR

echo "📥 Cloning repository..."
git clone https://github.com/Kirachon/health_check.git .

require_cmd openssl

echo "🔐 Generating required secrets..."
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(openssl rand -hex 16)}"
GRAFANA_ADMIN_PASSWORD="${GRAFANA_ADMIN_PASSWORD:-$(openssl rand -hex 16)}"
ALERT_WEBHOOK_TOKEN="${ALERT_WEBHOOK_TOKEN:-$(openssl rand -hex 32)}"

echo "🗝️  Writing Docker Compose secrets to $INSTALL_DIR/.env ..."
(umask 077; cat > "$INSTALL_DIR/.env" <<EOF
# Generated by deployment/install.sh (do not commit)
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
GRAFANA_ADMIN_PASSWORD=$GRAFANA_ADMIN_PASSWORD
ALERT_WEBHOOK_TOKEN=$ALERT_WEBHOOK_TOKEN
EOF
)
# umask 077 ensures the file is created with restrictive permissions.
chown root:root "$INSTALL_DIR/.env"
chmod 600 "$INSTALL_DIR/.env"

echo "🐍 Setting up Python virtual environments..."

# Server
cd $INSTALL_DIR/server
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
deactivate

# Agent
cd $INSTALL_DIR/agent
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
deactivate

echo "⚙️  Configuring server..."
cd $INSTALL_DIR/server
cp .env.example .env
# Generate secret key
SECRET_KEY=$(openssl rand -hex 32)
sed -i "s/your-secret-key-change-in-production-minimum-32-characters/$SECRET_KEY/" .env
sed -i "s|DATABASE_URL=.*|DATABASE_URL=postgresql://monitor_user:${POSTGRES_PASSWORD}@localhost:5433/health_monitor|" .env
sed -i "s|ALERT_WEBHOOK_TOKEN=.*|ALERT_WEBHOOK_TOKEN=${ALERT_WEBHOOK_TOKEN}|" .env

echo "🧱 Building GUI (requires Node.js 20.19+ or 22.12+)..."
cd $INSTALL_DIR/gui
require_cmd node
require_cmd npm
NODE_VERSION="$(node -v 2>/dev/null | sed 's/^v//')"
if [[ -z "$NODE_VERSION" ]]; then
  echo "❌ Unable to detect Node.js version."
  exit 1
fi
if ! version_ge "$NODE_VERSION" "20.19.0"; then
  echo "❌ Node.js $NODE_VERSION detected; Vite build requires Node.js 20.19+ or 22.12+."
  echo "   Install a supported Node.js version, then run: cd $INSTALL_DIR/gui && npm install && npm run build"
  exit 1
fi

cp .env.example .env
sed -i "s|^VITE_API_URL=.*|VITE_API_URL=https://${DOMAIN}/api/v1|" .env || true
sed -i "s|^VITE_VM_URL=.*|VITE_VM_URL=https://${DOMAIN}/victoriametrics|" .env || true
npm install
npm run build

echo "🐳 Starting Docker services..."
cd $INSTALL_DIR
docker-compose up -d

# Wait for services to be ready
echo "⏳ Waiting for services to start..."
sleep 10

echo "🔧 Setting up systemd services..."
cp deployment/systemd/health-monitor-api.service /etc/systemd/system/
cp deployment/systemd/health-monitor-agent.service /etc/systemd/system/

systemctl daemon-reload
systemctl enable health-monitor-api
systemctl enable health-monitor-agent
systemctl start health-monitor-api
systemctl start health-monitor-agent

echo "🌐 Configuring Nginx..."
cp deployment/nginx/health-monitor.conf /etc/nginx/sites-available/
sed -i "s/monitor.example.com/$DOMAIN/g" /etc/nginx/sites-available/health-monitor.conf
ln -sf /etc/nginx/sites-available/health-monitor.conf /etc/nginx/sites-enabled/
nginx -t && systemctl reload nginx

if [[ "$SKIP_CERTBOT" == "1" ]]; then
  echo "ℹ️  SKIP_CERTBOT=1 set; skipping Let's Encrypt. Install your internal TLS cert/key and update deployment/nginx/health-monitor.conf."
else
  echo "🔒 Setting up SSL with Let's Encrypt..."
  certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos --email "$EMAIL"
fi

echo "🔐 Setting file permissions..."
chown -R $SERVICE_USER:$SERVICE_USER $INSTALL_DIR
chmod -R 750 $INSTALL_DIR

# Keep root Docker secrets file locked down
chown root:root "$INSTALL_DIR/.env"
chmod 600 "$INSTALL_DIR/.env"

echo ""
echo "✅ Installation complete!"
echo ""
echo "Services:"
echo "  - API: https://$DOMAIN/api/v1/docs"
echo "  - GUI: https://$DOMAIN"
echo "  - Grafana: https://$DOMAIN/grafana"
echo ""
echo "Admin bootstrap:"
echo "  - Create the first admin via scripts/create_admin.py"
echo ""
echo "Next steps:"
echo "  1. Create the admin account"
echo "  2. Configure agent on monitored devices"
echo "  3. Set up email + internal webhook notifications in Grafana"
echo ""
echo "Service status:"
systemctl status health-monitor-api --no-pager
systemctl status health-monitor-agent --no-pager
